[:html
 [:head [:title (if (:title *metadata*)
                  (str (:title *metadata*) " | " (:site-name *metadata*))
                  (:site-name *metadata*))]
  [:link {:rel "stylesheet"
          :type "text/css"
          :href "/resources/stylesheets/default.css"}]]

 [:body
  [:div {:id "header"}
   [:div {:id "logo"} [:a {:href "/"} (:site-name *metadata*)]]
   [:div {:id "navigation"}
    [:a {:href "/"} "Home"]
    [:a {:href "/tags"} "Tags"]
    [:a {:href "/archives"} "Archives"]]]
  [:div {:id "content"}
   *content*]

  [:div {:id "footer"}
   "Site proudly generated by "
   [:a {:href "http://samrat.me/ecstatic"} "Ecstatic"]]

  ;; Snippet example: Google Analytics(snippets/ga.clj)
  (snippet "ga")]]
